# force_rebuild=true

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install --workspace client"
]

[phases.build]
cmds = [
  "npm run build --workspace client"
]

[start]
cmd = "npx serve -s client/dist -l $PORT"
