[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "npx serve -s client/dist -l $PORT"
